--- Cross-validation test: Lua implementation vs Python reference.
-- Loads test vectors generated by tools/generate_test_vectors.py
-- and asserts byte-for-byte match for every function.
--
-- This catches subtle divergences: byte order errors, off-by-one
-- in key lengths, incorrect XOR constants, padding differences, etc.

describe("Cross-validation against Python reference", function()
    local pdfcrypt = require("adobe.pdf.pdfcrypt")
    local rc4 = require("adobe.pdf.rc4")
    local nativecrypto = require("adobe.util.nativecrypto")

    it("loads test vectors fixture", function()
        local vectors = require("spec.integration.fixtures.test_vectors")
        assert.is.truthy(vectors)
        assert.is.truthy(next(vectors), "vectors table should not be empty")
    end)

    -- Load vectors once
    local vectors = require("spec.integration.fixtures.test_vectors")

    -- ================================================================
    -- genkey_v2 cross-validation
    -- ================================================================
    describe("genkey_v2", function()
        local bookkey = "\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b\x0c\x0d\x0e\x0f"

        -- objid=0, genno=0
        it("objid=0 genno=0", function()
            local result = pdfcrypt.genkey_v2(bookkey, 0, 0)
            assert.are.equal(vectors["genkey_v2_objid_0_genno_0"].expected, result)
        end)

        -- objid=1, genno=0
        it("objid=1 genno=0", function()
            local result = pdfcrypt.genkey_v2(bookkey, 1, 0)
            assert.are.equal(vectors["genkey_v2_objid_1_genno_0"].expected, result)
        end)

        -- objid=42, genno=0
        it("objid=42 genno=0", function()
            local result = pdfcrypt.genkey_v2(bookkey, 42, 0)
            assert.are.equal(vectors["genkey_v2_objid_42_genno_0"].expected, result)
        end)

        -- objid=0, genno=1
        it("objid=0 genno=1", function()
            local result = pdfcrypt.genkey_v2(bookkey, 0, 1)
            assert.are.equal(vectors["genkey_v2_objid_0_genno_1"].expected, result)
        end)

        -- objid=255, genno=255
        it("objid=255 genno=255", function()
            local result = pdfcrypt.genkey_v2(bookkey, 255, 255)
            assert.are.equal(vectors["genkey_v2_objid_255_genno_255"].expected, result)
        end)

        -- max 3-byte objid, max 2-byte genno
        it("max objid and genno", function()
            local result = pdfcrypt.genkey_v2(bookkey, 0xFFFFFF, 0xFFFF)
            assert.are.equal(vectors["genkey_v2_max_3byte_objid_max_2byte_genno"].expected, result)
        end)

        -- mixed values
        it("mixed values", function()
            local result = pdfcrypt.genkey_v2(bookkey, 0x123456, 0x789A)
            assert.are.equal(vectors["genkey_v2_mixed_values"].expected, result)
        end)

        -- Different key lengths
        it("8-byte key", function()
            local bk = "\x00\x01\x02\x03\x04\x05\x06\x07"
            local result = pdfcrypt.genkey_v2(bk, 100, 200)
            assert.are.equal(vectors["genkey_v2_bklen_8"].expected, result)
        end)

        it("16-byte key", function()
            local bk = bookkey
            local result = pdfcrypt.genkey_v2(bk, 100, 200)
            assert.are.equal(vectors["genkey_v2_bklen_16"].expected, result)
        end)

        it("24-byte key", function()
            local bk = "\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b\x0c\x0d\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17"
            local result = pdfcrypt.genkey_v2(bk, 100, 200)
            assert.are.equal(vectors["genkey_v2_bklen_24"].expected, result)
        end)

        -- Long key (20 bytes)
        it("20-byte key edge case", function()
            local bk = string.rep("\xab", 20)
            local result = pdfcrypt.genkey_v2(bk, 1, 1)
            assert.are.equal(vectors["genkey_v2_long_key"].expected, result)
        end)
    end)

    -- ================================================================
    -- genkey_v3 cross-validation
    -- ================================================================
    describe("genkey_v3", function()
        local bookkey = "\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b\x0c\x0d\x0e\x0f"

        it("objid=0 genno=0", function()
            local result = pdfcrypt.genkey_v3(bookkey, 0, 0)
            assert.are.equal(vectors["genkey_v3_objid_0_genno_0"].expected, result)
        end)

        it("objid=1 genno=0", function()
            local result = pdfcrypt.genkey_v3(bookkey, 1, 0)
            assert.are.equal(vectors["genkey_v3_objid_1_genno_0"].expected, result)
        end)

        it("objid=42 genno=0", function()
            local result = pdfcrypt.genkey_v3(bookkey, 42, 0)
            assert.are.equal(vectors["genkey_v3_objid_42_genno_0"].expected, result)
        end)

        it("objid=0 genno=1", function()
            local result = pdfcrypt.genkey_v3(bookkey, 0, 1)
            assert.are.equal(vectors["genkey_v3_objid_0_genno_1"].expected, result)
        end)

        it("objid=255 genno=255", function()
            local result = pdfcrypt.genkey_v3(bookkey, 255, 255)
            assert.are.equal(vectors["genkey_v3_objid_255_genno_255"].expected, result)
        end)

        it("max objid and genno", function()
            local result = pdfcrypt.genkey_v3(bookkey, 0xFFFFFF, 0xFFFF)
            assert.are.equal(vectors["genkey_v3_max_3byte_objid_max_2byte_genno"].expected, result)
        end)

        it("mixed values", function()
            local result = pdfcrypt.genkey_v3(bookkey, 0x123456, 0x789A)
            assert.are.equal(vectors["genkey_v3_mixed_values"].expected, result)
        end)

        it("8-byte key", function()
            local bk = "\x00\x01\x02\x03\x04\x05\x06\x07"
            local result = pdfcrypt.genkey_v3(bk, 100, 200)
            assert.are.equal(vectors["genkey_v3_bklen_8"].expected, result)
        end)

        it("16-byte key", function()
            local result = pdfcrypt.genkey_v3(bookkey, 100, 200)
            assert.are.equal(vectors["genkey_v3_bklen_16"].expected, result)
        end)

        it("24-byte key", function()
            local bk = "\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b\x0c\x0d\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17"
            local result = pdfcrypt.genkey_v3(bk, 100, 200)
            assert.are.equal(vectors["genkey_v3_bklen_24"].expected, result)
        end)

        -- Verify XOR constants
        it("zero xor verify", function()
            local result = pdfcrypt.genkey_v3(bookkey, 0, 0)
            assert.are.equal(vectors["genkey_v3_zero_xor_verify"].expected, result)
        end)
    end)

    -- ================================================================
    -- removeHardening cross-validation
    -- ================================================================
    describe("removeHardening", function()
        it("roundtrip with keyType=10", function()
            local v = vectors["removeHardening_roundtrip"]
            local result = pdfcrypt.removeHardening(
                v.hardenedData, v.keyType,
                v.resourceUUID, v.deviceUUID, v.fulfillmentUUID,
                nativecrypto.aes_cbc_decrypt
            )
            assert.are.equal(v.expected, result)
        end)

        it("keyType=3", function()
            local v = vectors["removeHardening_keytype_3"]
            local result = pdfcrypt.removeHardening(
                v.hardenedData, v.keyType,
                v.resourceUUID, v.deviceUUID, v.fulfillmentUUID,
                nativecrypto.aes_cbc_decrypt
            )
            assert.are.equal(v.expected, result)
        end)

        it("different resource UUID", function()
            local v = vectors["removeHardening_diff_resource"]
            local result = pdfcrypt.removeHardening(
                v.hardenedData, v.keyType,
                v.resourceUUID, v.deviceUUID, v.fulfillmentUUID,
                nativecrypto.aes_cbc_decrypt
            )
            assert.are.equal(v.expected, result)
        end)

        it("rem=0 edge case", function()
            local v = vectors["removeHardening_rem_zero"]
            local result = pdfcrypt.removeHardening(
                v.hardenedData, v.keyType,
                v.resourceUUID, v.deviceUUID, v.fulfillmentUUID,
                nativecrypto.aes_cbc_decrypt
            )
            assert.are.equal(v.expected, result)
        end)
    end)

    -- ================================================================
    -- RC4 cross-validation
    -- ================================================================
    describe("RC4", function()
        it("RFC 6229 5-byte key", function()
            local v = vectors["rc4_rfc_5byte_key"]
            local state = rc4.init(v.key)
            local result = rc4.crypt(state, v.data)
            assert.are.equal(v.expected, result)
        end)

        it("genkey_v2 + RC4 integrated", function()
            local v = vectors["genkey_v2_rc4_integrated"]
            local key = pdfcrypt.genkey_v2(v.bookKey, v.objid, v.genno)
            local state = rc4.init(key)
            local result = rc4.crypt(state, v.data)
            assert.are.equal(v.expected, result)
        end)

        it("genkey_v3 + RC4 integrated", function()
            local v = vectors["genkey_v3_rc4_integrated"]
            local key = pdfcrypt.genkey_v3(v.bookKey, v.objid, v.genno)
            local state = rc4.init(key)
            local result = rc4.crypt(state, v.data)
            assert.are.equal(v.expected, result)
        end)
    end)
end)
