#!/usr/bin/env python3
"""
Generate test vectors for cross-validating the Lua PDF decryption
implementation against the Python DeDRM reference.

Usage: python3 tools/generate_test_vectors.py > spec/integration/fixtures/test_vectors.lua

Each test vector captures exact byte-level inputs and expected outputs
so the Lua test can assert 1:1 fidelity with the Python reference.
"""

import hashlib
import struct
import sys

# --- Pure Python implementations matching ineptpdf.py exactly ---

def genkey_v2(decrypt_key, objid, genno):
    """Match ineptpdf.py genkey_v2 lines 1764-1770 exactly."""
    objid_bytes = struct.pack('<L', objid)[:3]
    genno_bytes = struct.pack('<L', genno)[:2]
    key = decrypt_key + objid_bytes + genno_bytes
    h = hashlib.md5(key)
    return h.digest()[:min(len(decrypt_key) + 5, 16)]

def genkey_v3(decrypt_key, objid, genno):
    """Match ineptpdf.py genkey_v3 lines 1772-1779 exactly."""
    objid_bytes = struct.pack('<L', objid ^ 0x3569ac)
    genno_bytes = struct.pack('<L', genno ^ 0xca96)
    key = decrypt_key
    key += bytes([objid_bytes[0], genno_bytes[0], objid_bytes[1],
                  genno_bytes[1], objid_bytes[2]]) + b'sAlT'
    h = hashlib.md5(key)
    return h.digest()[:min(len(decrypt_key) + 5, 16)]

def hex_to_lua(b):
    """Format bytes as a Lua string with \\x escapes."""
    if isinstance(b, str):
        b = b.encode('ascii')
    parts = []
    for byte in b:
        parts.append(f"\\x{byte:02x}")
    return '"' + ''.join(parts) + '"'

def emit_vector(name, inputs, expected):
    """Emit a Lua table entry."""
    print(f'    ["{name}"] = {{')
    print(f'        description = "{name}",')
    for k, v in inputs.items():
        if isinstance(v, bytes):
            print(f'        {k} = {hex_to_lua(v)},')
        elif isinstance(v, int):
            print(f'        {k} = {v},')
        elif isinstance(v, str):
            print(f'        {k} = "{v}",')
        else:
            print(f'        {k} = "{v}",')
    if expected is not None:
        print(f'        expected = {hex_to_lua(expected)},')
    else:
        print(f'        expected = nil,')
    print('    },')

def main():
    print("-- Auto-generated test vectors for cross-validation against")
    print("-- the Python DeDRM reference (ineptpdf.py).")
    print("-- Generated by: tools/generate_test_vectors.py")
    print("-- DO NOT EDIT BY HAND.")
    print()
    print("local vectors = {")

    # ================================================================
    # genkey_v2 tests
    # ================================================================
    bookkey_v2 = bytes(range(16))  # 00 01 02 ... 0f

    test_cases_v2 = [
        (0, 0, "objid_0_genno_0"),
        (1, 0, "objid_1_genno_0"),
        (42, 0, "objid_42_genno_0"),
        (0, 1, "objid_0_genno_1"),
        (255, 255, "objid_255_genno_255"),
        (0xFFFFFF, 0xFFFF, "max_3byte_objid_max_2byte_genno"),
        (0x123456, 0x789A, "mixed_values"),
    ]

    for objid, genno, desc in test_cases_v2:
        name = f"genkey_v2_{desc}"
        expected = genkey_v2(bookkey_v2, objid, genno)
        emit_vector(name, {
            "func_name": "genkey_v2",
            "bookKey": bookkey_v2,
            "objid": objid,
            "genno": genno,
        }, expected)

    # Test with different book key lengths
    for bk_len in [8, 16, 24]:
        bk = bytes(range(bk_len))
        expected = genkey_v2(bk, 100, 200)
        emit_vector(f"genkey_v2_bklen_{bk_len}", {
            "func_name": "genkey_v2",
            "bookKey": bk,
            "objid": 100,
            "genno": 200,
        }, expected)

    # Test edge: genkey_v2 output length is min(keylen+5, 16)
    bk = bytes([0xAB] * 20)  # 20-byte key
    expected = genkey_v2(bk, 1, 1)
    emit_vector("genkey_v2_long_key", {
        "func_name": "genkey_v2",
        "bookKey": bk,
        "objid": 1,
        "genno": 1,
    }, expected)

    # ================================================================
    # genkey_v3 tests
    # ================================================================
    for objid, genno, desc in test_cases_v2:
        name = f"genkey_v3_{desc}"
        expected = genkey_v3(bookkey_v2, objid, genno)
        emit_vector(name, {
            "func_name": "genkey_v3",
            "bookKey": bookkey_v2,
            "objid": objid,
            "genno": genno,
        }, expected)

    for bk_len in [8, 16, 24]:
        bk = bytes(range(bk_len))
        expected = genkey_v3(bk, 100, 200)
        emit_vector(f"genkey_v3_bklen_{bk_len}", {
            "func_name": "genkey_v3",
            "bookKey": bk,
            "objid": 100,
            "genno": 200,
        }, expected)

    # Verify the XOR constants are applied correctly
    # objid ^ 0x3569ac, genno ^ 0xca96
    expected = genkey_v3(bookkey_v2, 0, 0)
    emit_vector("genkey_v3_zero_xor_verify", {
        "func_name": "genkey_v3",
        "bookKey": bookkey_v2,
        "objid": 0,
        "genno": 0,
    }, expected)

    # ================================================================
    # removeHardening tests (requires pycryptodome)
    # ================================================================
    try:
        from Crypto.Cipher import AES
        from uuid import UUID

        real_key = bytes([0xDE, 0xAD, 0xBE, 0xEF] * 4)  # 16 bytes

        # Test 1: round-trip with keyType=10
        keytype = "10"
        r_uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
        d_uuid = "b2c3d4e5-f6a7-8901-bcde-f12345678901"
        f_uuid = "c3d4e5f6-a7b8-9012-cdef-123456789012"

        r = UUID(r_uuid)
        d = UUID(d_uuid)
        f = UUID(f_uuid[:36])
        iv = UUID(int=r.int ^ d.int ^ f.int).bytes

        rem = int(keytype, 10) % 16
        H = hashlib.sha256(keytype.encode("ascii")).digest()
        kek = H[2*rem : 16 + rem] + H[rem : 2*rem]

        pad = 16 - (len(real_key) % 16)
        padded = real_key + bytes([pad] * pad)
        hardened = AES.new(kek, AES.MODE_CBC, iv).encrypt(padded)

        # Verify round-trip
        recovered = AES.new(kek, AES.MODE_CBC, iv).decrypt(hardened)
        reclen = recovered[-1]
        recovered = recovered[:-reclen]
        assert recovered == real_key

        emit_vector("removeHardening_roundtrip", {
            "func_name": "removeHardening",
            "func_name": "removeHardening",
            "hardenedData": hardened,
            "keyType": keytype,
            "resourceUUID": r_uuid,
            "deviceUUID": d_uuid,
            "fulfillmentUUID": f_uuid,
        }, real_key)

        # Test 2: keyType=3
        kt2 = "3"
        rem2 = int(kt2, 10) % 16
        H2 = hashlib.sha256(kt2.encode("ascii")).digest()
        kek2 = H2[2*rem2 : 16 + rem2] + H2[rem2 : 2*rem2]
        hardened2 = AES.new(kek2, AES.MODE_CBC, iv).encrypt(padded)

        emit_vector("removeHardening_keytype_3", {
            "func_name": "removeHardening",
            "hardenedData": hardened2,
            "keyType": kt2,
            "resourceUUID": r_uuid,
            "deviceUUID": d_uuid,
            "fulfillmentUUID": f_uuid,
        }, real_key)

        # Test 3: different resource UUID
        r_uuid3 = "00000000-0000-0000-0000-000000000001"
        r3 = UUID(r_uuid3)
        iv3 = UUID(int=r3.int ^ d.int ^ f.int).bytes
        hardened3 = AES.new(kek, AES.MODE_CBC, iv3).encrypt(padded)

        emit_vector("removeHardening_diff_resource", {
            "func_name": "removeHardening",
            "hardenedData": hardened3,
            "keyType": keytype,
            "resourceUUID": r_uuid3,
            "deviceUUID": d_uuid,
            "fulfillmentUUID": f_uuid,
        }, real_key)

        # Test 4: keyType with rem=0 edge case
        kt4 = "16"
        rem4 = int(kt4, 10) % 16
        H4 = hashlib.sha256(kt4.encode("ascii")).digest()
        kek4 = H4[2*rem4 : 16 + rem4] + H4[rem4 : 2*rem4]
        hardened4 = AES.new(kek4, AES.MODE_CBC, iv).encrypt(padded)

        emit_vector("removeHardening_rem_zero", {
            "func_name": "removeHardening",
            "hardenedData": hardened4,
            "keyType": kt4,
            "resourceUUID": r_uuid,
            "deviceUUID": d_uuid,
            "fulfillmentUUID": f_uuid,
        }, real_key)

    except ImportError:
        print("-- WARNING: pycryptodome not installed, skipping removeHardening vectors", file=sys.stderr)

    # ================================================================
    # RC4 decryption tests
    # ================================================================
    try:
        from Crypto.Cipher import ARC4

        # RFC 6229 test vector
        key_rfc = bytes([0x01, 0x02, 0x03, 0x04, 0x05])
        data_rfc = bytes(range(32))
        expected_rfc = ARC4.new(key_rfc).decrypt(data_rfc)

        emit_vector("rc4_rfc_5byte_key", {
            "func_name": "rc4",
            "key": key_rfc,
            "data": data_rfc,
        }, expected_rfc)

        # Integrated: genkey_v2 + RC4
        per_obj_key = genkey_v2(bookkey_v2, 42, 0)
        test_data = bytes([0xFF] * 64)
        expected = ARC4.new(per_obj_key).decrypt(test_data)

        emit_vector("genkey_v2_rc4_integrated", {
            "func_name": "rc4_with_genkey",
            "bookKey": bookkey_v2,
            "objid": 42,
            "genno": 0,
            "data": test_data,
        }, expected)

        # Integrated: genkey_v3 + RC4
        per_obj_key_v3 = genkey_v3(bookkey_v2, 42, 0)
        expected_v3 = ARC4.new(per_obj_key_v3).decrypt(test_data)

        emit_vector("genkey_v3_rc4_integrated", {
            "func_name": "rc4_with_genkey",
            "bookKey": bookkey_v2,
            "objid": 42,
            "genno": 0,
            "genkey_version": 3,
            "data": test_data,
        }, expected_v3)

    except ImportError:
        print("-- WARNING: pycryptodome not installed, skipping RC4 vectors", file=sys.stderr)

    # ================================================================
    # SHA-256 key derivation verification
    # ================================================================
    for kt in ["0", "2", "3", "10", "16"]:
        H = hashlib.sha256(kt.encode("ascii")).digest()
        emit_vector(f"sha256_keytype_{kt}", {
            "func_name": "sha256_bin",
            "input": kt,
        }, H)

    # Verify KEK derivation formula
    for kt_str in ["3", "10", "16"]:
        kt = int(kt_str)
        rem = kt % 16
        H = hashlib.sha256(kt_str.encode("ascii")).digest()
        kek = H[2*rem : 16 + rem] + H[rem : 2*rem]
        emit_vector(f"kek_derive_{kt_str}", {
            "func_name": "kek_derive",
            "keyType": kt_str,
        }, kek)

    print("}")
    print()
    print("return vectors")

if __name__ == "__main__":
    main()
